version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        update-types:
          ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/deployer"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/testing/integration"
    schedule:
      interval: "weekly"

  - package-ecosystem: npm
    directory: "/client/pwa"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        update-types:
          ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: npm
    directory: "/cloud-function"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        update-types:
          ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: npm
    directory: "/lib/locale-utils"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        update-types:
          ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: npm
    directory: "/lib/pong"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        update-types:
          ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: npm
    directory: "/lib/slug-utils"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        update-types:
          ["version-update:semver-minor", "version-update:semver-patch"]

    # This forces the Dependabot commit messages to conform to something
    # our auto-merge workflow can always cope with.
    # See https://github.com/ahmadnassri/action-dependabot-auto-merge/issues/31#issuecomment-718779806
    commit-message:
      prefix: build
      prefix-development: chore
      include: scope
